; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.3.14 on Fri Oct 28 2022 10:29:37 GMT+0200 (Central European Summer Time)
G91                 ; relative positioning
G1 H1 Y10 F1500
G1 H1 Y-505 F800    ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y5 F1500      ; go back a few mm
G1 H1 Y-505 F250    ; move slowly to Y axis endstop once more (second pass)
M400