; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.3.14 on Fri Oct 28 2022 10:29:37 GMT+0200 (Central European Summer Time)
G90                    ; absolute positioning
G92 Z0                 ; set Z position to axis minimum 
