; Configuration file for Duet 3 MB 6HC + 3HC EXPANSION BOARD
; executed by the firmware on start-up
; Generated by OMD3D / BLACKBELT-3D on TUE Feb 07 2024 18:37:19 GMT+0100 (Central European Standard Time)

; General_________________________________________________________________________________________________________________

M550 P"BB_Ascent Sn OMD3D-BB-226" ; set hostname

;machine configuration "BB XL DUAL HEAD IDEX"

; Accessories_________________________________________________________________________________________________________________

M575 P1 S0 B57600                                ; configure PanelDue support

; Network_________________________________________________________________________________________________________________

M552 P0.0.0.0 S1                                 ; configure Ethernet adapter
M586 P0 S1                                       ; configure HTTP

; Wait a moment for the CAN expansion boards to become available
G4 S2

; Smart Drivers_________________________________________________________________________________________________________________

M569 P0.0 S0                                    ; driver 0.0 goes backwards (X axis/Primary)
M569 P0.1 S1                                    ; driver 0.1 goes forwards (Y axis/Y_LEFT)
M569 P0.2 S0                                    ; driver 0.2 goes backwards (Y axis/Y_RIGHT)
M569 P0.3 S1                                    ; driver 0.3 goes forwards (Z axis)
M569 P0.4 S0                                    ; driver 0.4 goes backwards (U axis/Secondary) ONLY FOR DUAL HEAD ST + XL
M569 P0.5 S1                                    ; driver 0.5 goes forwards (extruder 3/E1_A secondary internal) ONLY FOR DUAL HEAD ST + XL
M569 P1.0 S0                                    ; driver 1.0 goes backwards (extruder 0/E0 Primary)
M569 P1.1 S1                                    ; driver 1.1 goes forwards (extruder 1/E0_A Primary internal)
M569 P1.2 S0                                    ; driver 1.2 goes backwards (extruder 2/E1 Secondary) ONLY FOR DUAL HEAD ST + XL

; Drive mapping for DUAL HEAD ST + XL___________________________________________________________________________________________

;M584 X0.0 Y0.1:0.2 Z0.3 U0.4 E1.0:1.1:1.2:0.5               ; set drive mapping
;M350 X16 Y16 Z16 U16 E16:16:16:16 I1                        ; configure microstepping with interpolation
;M92 X100 Y88.89 Z318.565257525 U100 E676.34:676.34:676.34:676.34   ; configure steps per mm
;M566 X600 Y600 Z600 U600 E120:120:120:120                   ; !!!!!!EXPERIMENTAL!!!!! ; set maximum instantaneous speed changes (mm/min)
; ORIGINAL SETTING M566 X300 Y300 Z300 U300 E120:120:120:120                   ; set maximum instantaneous speed changes (mm/min)
;M203 X15000 Y15000 Z3000 U15000 E3600:3600:3600:3600           ; !!!!!!EXPERIMENTAL!!!!! ; set maximum speeds (mm/min)
; ORIGINAL SETTING M203 X9000 Y9000 Z3000 U9000 E3600:3600:3600:3600           ; set maximum speeds (mm/min)
;M201 X1000 Y1000 Z500 U1000 E350:350:350:350                   ; !!!!!!EXPERIMENTAL!!!!! ; set accelerations (mm/s^2)
; ORIGINAL SETTING M201 X700 Y700 Z500 U700 E250:250:250:250                   ; set accelerations (mm/s^2)
;M906 X1400 Y1400 Z1000 U1400 E720:720:720:720 I50           ; set motor currents (mA) and motor idle factor in per cent
;M84 S360                                                     ; Set idle timeout

; Drive mapping for SINGLE HEAD ST + XL___________________________________________________________________________________________

M584 X0.0 Y0.1:0.2 Z0.3 E1.0:1.1                            ; set drive mapping
M350 X16 Y16 Z16 E16:16 I1                                  ; configure microstepping with interpolation
M92 X100 Y88.89 Z317.41 E676.34:676.34                      ; configure steps per mm
M566 X600 Y600 Z600 E120:120                                ; set maximum instantaneous speed changes (mm/min)
M203 X15000 Y15000 Z3000 E3600:3600                           ; set maximum speeds (mm/min)
M201 X1000 Y1000 Z500 E350:350                                ; set accelerations (mm/s^2)
M906 X1400 Y1400 Z1000 E720:720 I50                         ; set motor currents (mA) and motor idle factor in per cent
M84 S180                                                     ; Set idle timeout


; Axis Limits______FOR BB ST SINGLE HEAD___________________________________________________________________________________________________________

;M208 X325 Y485 Z99999999                                    ; set axis maxima
;M208 X-0 Y0 U0 Z0 S1 									     ; Set axis minimum

; Axis Limits______FOR BB ST DUAL HEAD___________________________________________________________________________________________________________

;M208 X260 Y485 U260 Z99999999                               ; set axis maxima
;M208 X-0 Y0 U0 Z0 S1 									     ; Set axis minimum

; Axis Limits______FOR BB XL SINGLE HEAD___________________________________________________________________________________________________________

M208 X500 Y485 Z99999999                                    ; set axis maxima
M208 X-0 Y0 U0 Z0 S1 									     ; Set axis minimum


; Axis Limits______FOR BB XL DUAL HEAD___________________________________________________________________________________________________________

;M208 X438 Y485 U438 Z99999999                                ; set axis maxima
;M208 X-0 Y0 U0 Z0 S1 									     ; Set axis minimum


; Endstops_________________________________________________________________________________________________________________

M574 X1 P"io1.in" S1                                        ; configure X axis endstop
M574 Y1 P"io3.in" S1                                        ; configure Y axis endstop
M574 Z0                                                     ; configure Z axis endstop
M574 U2 P"io2.in" S1                                        ; configure U axis endstop

; Sensors_________________________________________________________________________________________________________________

M308 S0 P"temp0" Y"thermistor" A"Bed0" T100000 B4725 C7.06e-8                   ; configure sensor #0 FOR BB ST + XL
M308 S1 P"temp1" Y"thermistor" A"Bed1" T100000 B4725 C7.06e-8                   ; configure sensor #1 ONLY FOR BB XL
;M308 S2 P"temp2" Y"thermistor" A"Bed2" T100000 B4725 C7.06e-8                  ; configure sensor #2 ONLY FOR SPECIAL CONFIGURATIONS
;M308 S3 P"temp3" Y"thermistor" A"Bed3" T100000 B4725 C7.06e-8                  ; configure sensor #3 ONLY FOR SPECIAL CONFIGURATIONS
M308 S4 P"1.temp0" Y"thermistor" A"E0" T4606017 B5848 C5.548428e-8 R4700        ; configure sensor #4 FOR BB ST + XL
;M308 S5 P"1.temp1" Y"thermistor" A"E1" T4606017 B5848 C5.548428e-8 R4700        ; configure sensor #5 ONLY FOR DUAL HEAD ST + XL


; Heaters_________________________________________________________________________________________________________________

;BED HEATERS

;FOR BB ST + XL
M950 H0 C"out1" T0                                                      ; create heater #0 
M143 H0 P0 T0 C0 S200 A0                                                ; configure heater monitor #0 for heater #0
M307 H0 R0.417 K0.945:0.000 D3.16 E1.35 S1.00 B0                        ; configure model of heater #0

;ONLY FOR BB XL
M950 H1 C"out2" T1                                                      ; create heater #1
M143 H1 P0 T1 C0 S200 A0                                                ; configure heater monitor #0 for heater #1
M307 H1 R0.382 K0.672:0.000 D6.68 E1.35 S1.00 B0                        ; configure model of heater #1

;ONLY FOR SPECIAL CONFIGURATIONS
;M950 H2 C"out3" T2                                                     ; create heater #2
;M143 H2 P0 T1 C0 S200 A0                                               ; configure heater monitor #0 for heater #2
;M307 H2 R2.43 D5.5 E1.35 K0.56 B1                                      ; configure model of heater #2

;ONLY FOR SPECIAL CONFIGURATIONS
;M950 H3 C"out4" T3                                                     ; create heater #3
;M143 H3 P0 T1 C0 S200 A0                                               ; configure heater monitor #0 for heater #3
;M307 H3 R2.43 D5.5 E1.35 K0.56 B1                                      ; configure model of heater #3

;EXTRUDER HEATERS

;FOR BB ST + XL
M950 H4 C"1.out0" T4                                                    ; create heater #4
M143 H4 P0 T4 C0 S495 A0                                                ; configure heater monitor #0 for heater #4
M307 H4 R2.205 K0.221:0.161 D6.67 E1.35 S1.00 B0                      ; Heating process parameters for 24V a system

;FOR BB ST + XL DUAL HEAD
;M950 H5 C"1.out1" T5                                                    ; create heater #5
;M143 H5 P0 T5 C0 S495 A0                                                ; configure heater monitor #0 for heater #5
;M307 H5 R2.068 K0.286:0.254 D11.68 E1.35 S1.00 B0                        ; Heating process parameters for 24V a system

; Heated beds_________________________________________________________________________________________________________________

M140 P0 H0 S0 R0                                                             ; configure heated bed #0  FOR BB ST + XL
M140 P1 H1 S0 R0                                                             ; configure heated bed #1  ONLY FOR BB XL
;M140 P2 H2                                                             ; configure heated bed #2  ONLY FOR SPECIAL CONFIGURATIONS
;M140 P3 H3                                                             ; configure heated bed #3  ONLY FOR SPECIAL CONFIGURATIONS

; Fans_________________________________________________________________________________________________________________

;FOR BB ST + XL
M950 F0 C"1.out3"                                                       ; create fan #0, JF was out.4
M106 P0 C"HF-E0" S0 B0.1 H3 T45                                         ; configure fan #0, JF was H4

;FOR BB ST + XL DUAL HEAD
;M950 F4 C"1.out5"                                                       ; create fan #1
;M106 P4 C"HF-E1" S0 B0.1 H5 T45                                         ; configure fan #1

;FOR BB ST + XL
M950 F2 C"1.out6"                                                       ; create fan #2
M106 P2 C"PF-E0" S0 L0 X1 B1                                            ; configure fan #2

;FOR BB ST + XL DUAL HEAD
;M950 F3 C"1.out7"                                                       ; create fan #3
;M106 P3 C"PF-E1" S0 L0 X1 B1                                            ; configure fan #3

;FOR BB ST + XL
M950 F1 C"1.out8"                                                       ; create fan #4
M106 P1 C"SF" S0 L0 X1 B1                                               ; configure fan #4

; Tools_________________________________________________________________________________________________________________

; X TOOL_________________________________________________________________________________________________________________

M563 P0 S"T0" D0:1 H4 F2;:1                                     ; create tool #0
M568 P0 R0 S0                                                  ; set initial tool #0 active and standby temperatures to 0C
M567 P0 E1:1                                                   ; set mixing ratios for tool #0
G10 P0 X0 Y0 Z0 R0 S0       								   ; set tool 0 axis offsets

; U TOOL_________ONLY FOR BB ST + XL DUAL HEAD___________________________________________________________________________

;M563 P1 S"T1" D2:3 H5 X3 F3;:1                                  ; create tool #1
;M568 P1 R0 S0                                                  ; set initial tool #1 active and standby temperatures to 0C
;M567 P1 E1:1                                                   ; set mixing ratios for tool #1
;G10 P1 Y0 U0 Z0 R0 S200                               	       ; set tool 1 axis offsets

; X+U COPY TOOL____ONLY FOR BB ST DUAL HEAD_____________________________________________________________________________________________________________

;M563 P2 S"T2" D0:1:2:3 H4:5 X0:3 F2:3;:1                       ; create tool #2
;M568 P2 R0 S0                                                 ; set initial tool #1 active and standby temperatures to 0C
;M567 P2 E1:1:1:1                                              ; set mixing ratios for tool #2
;G10 P2 X0 Y0 Z0 U-100 R0 S200 								   ; set tool offsets and temperatures

; X+U COPY TOOL____ONLY FOR BB XL DUAL HEAD_____________________________________________________________________________________________________________

;M563 P2 S"T2" D0:1:2:3 H4:5 X0:3 F2:3:1                        ; create tool #2
;M568 P2 R0 S0                                                  ; set initial tool #1 active and standby temperatures to 0C
;M567 P2 E1:1:1:1                                               ; set mixing ratios for tool #2
;G10 P2 X0 Y0 Z0 U-190 R0 S0 								   ; set tool offsets and temperatures

; Miscellaneous

M591 D0 P7 C"1.io1.in" S1 R10:300 E10 L2.95                    ; filament sensor on E0
;M591 P1 C"1.io1.in" S1 D0				                       ; filament sensor on E0
M591 D0							                               ; display filament sensor parameters for extruder drive0
;M591 D2 P7 C"1.io2.in" S1 R10:300 E10 L2.95				                       ; filament sensor on E1
;M591 P1 C"1.io2.in" S1 D2				                       ; filament sensor on E1
;M591 D2							                               ; display filament sensor parameters for extruder drive1

; Automatic power saving_____________________________________________________________________________________________________________________________

M911 S21.0 R23.5 P"M913 X0 Y0 U0 G91 M83 G1 E-5 F1000"         ; Set voltage thresholds and actions to run on power loss. Power Failure Pause


M98 P"JobQueue/config.g"